#!/bin/bash
rm ".gitattributes" -rf 
git lfs track  "C++\C++  Qt设计模式（第2版）.pdf"  
git lfs track  "C++\C++17- 参考手册-中文版-PDF\C++ 参考手册 第一部分 2017.12.20.pdf"  
git lfs track  "C++\Linux C程序设计大全\Linux C程序设计大全.7z.001"  
git lfs track  "C++\Linux C程序设计大全\Linux C程序设计大全.7z.002"  
git lfs track  "C++\Linux C程序设计大全\Linux C程序设计大全.7z.003"  
git lfs track  "C++\Linux C程序设计大全\Linux C程序设计大全.7z.004"  
git lfs track  "C++\Linux C程序设计大全\Linux C程序设计大全.pdf"  
git lfs track  "database\NoSQL\NoSQL数据库技术实战.pdf"  
git lfs track  "JAVA\java se\Java JDK 8学习笔记  清华大学出版社.pdf"  
git lfs track  "JAVA\java se\JAVA_API_1.7en.chm"  
git lfs track  "JAVA\java se\Java从入门到精通 第三版.pdf"  
git lfs track  "JAVA\java se\Java网络编程.第3版.哈诺德.扫描版.pdf"  
git lfs track  "JAVA\java web\html&css&js\CSS权威指南 第3版.pdf"  
git lfs track  "JAVA\java web\Java.Web.开发详解.XML.XSLT.Servlet.JSP.深入剖析实例应用.pdf"  
git lfs track  "JAVA\java web\学通Java.Web的24堂课.陈丹丹.卢瀚.扫描版.pdf"  
git lfs track  "JAVA\java web\深入体验Java.Web开发内幕-核心基础-张孝祥著.pdf"  
git lfs track  "JAVA\java web\深入体验Java.Web项目开发.张玲玲.扫描版.pdf"  
git lfs track  "JAVA\java web\深入体验Java_Web开发内幕-核心基础-张孝祥著.pdf"  
git lfs track  "linux\深入Linux内核架构(中文版)\深入Linux内核架构(中文版)@www.jqhtml.com.pdf"  
git lfs track  "linux\深入Linux内核架构(中文版)\深入Linux内核架构(中文版)@www.jqhtml.com.z01"  
git lfs track  "linux\深入Linux内核架构(中文版)\深入Linux内核架构(中文版)@www.jqhtml.com.z02"  
git lfs track  "linux\深入理解linux内核（中文第三版）.pdf"  
git lfs track  "UML&面向对象设计\UML用户指南(第2版).pdf"  
git lfs track  "基础理论\云计算\Hadoop\Hadoop 2.X HDFS源码剖析.pdf"  
git lfs track  "基础理论\云计算\Hadoop\Hadoop基础教程.pdf"  
git lfs track  "基础理论\云计算\《云计算》-刘鹏-第二版-扫描版.pdf"  
git lfs track  "基础理论\云计算\云计算-概念、技术与架构.pdf"  
git lfs track  "基础理论\云计算\虚拟化\Docker 容器与容器云（第2版）-扫描版.pdf"  
git lfs track  "基础理论\云计算\虚拟化\KVM虚拟化技术 实战与原理解析 任永杰 单海涛 .pdf"  
git lfs track  "基础理论\分布式\2018分布式计算\分布式系统概念与设计 原书第5版.pdf"  
git lfs track  "基础理论\模式识别与机器学习\周志华-机器学习.pdf"  
git lfs track  "基础理论\汇编\Inter汇编语言程序设计（第五版）.pdf"  
git lfs track  "基础理论\离散数学及其应用\离散数学及其应用（原书第6版）.pdf"  
git lfs track  "基础理论\算法\屈婉玲-算法设计与分析-第2版.pdf"  
git lfs track  "基础理论\算法\算法导论中文版-第二版.pdf"  
git lfs track  "数据恢复技术(第二版).pdf"  
